//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.Enums
{
    public enum ItemEffectType
    {
        /// <summary>
        /// 经验值
        /// </summary>
        Exp = 0,
        /// <summary>
        /// 金币
        /// </summary>
        Coin = 1,
        /// <summary>
        /// 钻石
        /// </summary>
        Diamond = 2,
        /// <summary>
        /// 票
        /// </summary>
        Ticket = 3,
    }
}
