//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg
{

public abstract partial class BuffCfg :  Bright.Config.BeanBase 
{
    public BuffCfg(ByteBuf _buf) 
    {
        buffId = _buf.ReadInt();
        buffName = _buf.ReadString();
        buffType = (BuffTypeEnum)_buf.ReadInt();
        attacher = (AttachTypeEnum)_buf.ReadInt();
        staticPosType = (StaticPosTypeEnum)_buf.ReadInt();
        if(_buf.ReadBool()){ impacter = TargetCfg.DeserializeTargetCfg(_buf); } else { impacter = null; }
        buffDelay = _buf.ReadInt();
        buffInterval = _buf.ReadInt();
        buffDuration = _buf.ReadInt();
        buffAudio = _buf.ReadString();
        buffEffect = _buf.ReadString();
        hitTickAudio = _buf.ReadString();
        PostInit();
    }

    public static BuffCfg DeserializeBuffCfg(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case NormalBuffCfg.__ID__: return new NormalBuffCfg(_buf);
            case DamageBuffCfg_DynamicGroup.__ID__: return new DamageBuffCfg_DynamicGroup(_buf);
            case DamageBuffCfg_StaticGroup.__ID__: return new DamageBuffCfg_StaticGroup(_buf);
            case ArthurMarkBuffCfg.__ID__: return new ArthurMarkBuffCfg(_buf);
            case CommonModifySkillBuffCfg.__ID__: return new CommonModifySkillBuffCfg(_buf);
            case ExecuteDamageBuffCfg.__ID__: return new ExecuteDamageBuffCfg(_buf);
            case HPCureBuffCfg.__ID__: return new HPCureBuffCfg(_buf);
            case HouyiMixedMultiScatterBuffCfg.__ID__: return new HouyiMixedMultiScatterBuffCfg(_buf);
            case HouyiMultipleArrowBuffCfg.__ID__: return new HouyiMultipleArrowBuffCfg(_buf);
            case HouyiMultipleSkillModifyBuffCfg.__ID__: return new HouyiMultipleSkillModifyBuffCfg(_buf);
            case HouyiPasvAttackSpeedBuffCfg.__ID__: return new HouyiPasvAttackSpeedBuffCfg(_buf);
            case HouyiScatterArrowBuffCfg.__ID__: return new HouyiScatterArrowBuffCfg(_buf);
            case HouyiScatterSkillModifyBuffCfg.__ID__: return new HouyiScatterSkillModifyBuffCfg(_buf);
            case MoveSpeedBuffCfg.__ID__: return new MoveSpeedBuffCfg(_buf);
            case StunBuffCfg_DynamicTime.__ID__: return new StunBuffCfg_DynamicTime(_buf);
            case TargetFlashMoveBuffCfg.__ID__: return new TargetFlashMoveBuffCfg(_buf);
            default: throw new SerializationException();
        }
    }

    public int buffId { get; private set; }
    public string buffName { get; private set; }
    /// <summary>
    /// buff类型，用来创建不同类型的buff
    /// </summary>
    public BuffTypeEnum buffType { get; private set; }
    /// <summary>
    /// buff附着目标
    /// </summary>
    public AttachTypeEnum attacher { get; private set; }
    public StaticPosTypeEnum staticPosType { get; private set; }
    /// <summary>
    /// buff作用目标，如果为null默认影响附着对象
    /// </summary>
    public TargetCfg impacter { get; private set; }
    public int buffDelay { get; private set; }
    /// <summary>
    /// buff效果触发频率(比如持续1秒1次)，如果为0就只调用Start，LogicTick不会调用到Tick
    /// </summary>
    public int buffInterval { get; private set; }
    /// <summary>
    /// buff持续时间（不包含delay）0：生效1次，-1：永久生效
    /// </summary>
    public int buffDuration { get; set; }
    public string buffAudio { get; private set; }
    public string buffEffect { get; private set; }
    public string hitTickAudio { get; private set; }


    public virtual void Resolve(Dictionary<string, object> _tables)
    {
        impacter?.Resolve(_tables);
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
        impacter?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "buffId:" + buffId + ","
        + "buffName:" + buffName + ","
        + "buffType:" + buffType + ","
        + "attacher:" + attacher + ","
        + "staticPosType:" + staticPosType + ","
        + "impacter:" + impacter + ","
        + "buffDelay:" + buffDelay + ","
        + "buffInterval:" + buffInterval + ","
        + "buffDuration:" + buffDuration + ","
        + "buffAudio:" + buffAudio + ","
        + "buffEffect:" + buffEffect + ","
        + "hitTickAudio:" + hitTickAudio + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
