//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg
{
    /// <summary>
    /// buff类型，用来创建不同类型的buff
    /// </summary>
    public enum BuffTypeEnum
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 移动攻击
        /// </summary>
        MoveAttack = 1,
        /// <summary>
        /// 治疗
        /// </summary>
        HPCure = 2,
        /// <summary>
        /// 单体击飞
        /// </summary>
        Knockup_Single = 3,
        /// <summary>
        /// 群体击飞
        /// </summary>
        Knockup_Group = 4,
        /// <summary>
        /// 单体沉默
        /// </summary>
        Silense_Single = 5,
        /// <summary>
        /// 群体沉默
        /// </summary>
        Silense_Group = 6,
        /// <summary>
        /// 单体眩晕
        /// </summary>
        Stun_Single = 7,
        /// <summary>
        /// 群体眩晕
        /// </summary>
        Stun_Group = 8,
        /// <summary>
        /// 动态时间眩晕：例如Houyi3技能
        /// </summary>
        Stun_Single_DynamicTime = 9,
        /// <summary>
        /// 单体加速
        /// </summary>
        MoveSpeed_Single = 10,
        /// <summary>
        /// 动态群体移速
        /// </summary>
        MoveSpeed_DynamicGroup = 11,
        /// <summary>
        /// 静态群体移速
        /// </summary>
        MoveSpeed_StaticGroup = 12,
        /// <summary>
        /// 单体牵引
        /// </summary>
        Hook_Single = 13,
        /// <summary>
        /// 群体牵引
        /// </summary>
        Hook_Group = 14,
        /// <summary>
        /// 动态群体伤害
        /// </summary>
        Damage_DynamicGroup = 15,
        /// <summary>
        /// 静态群体伤害
        /// </summary>
        Damage_StaticGroup = 16,
        /// <summary>
        /// 替换普攻：例如Arthur1技能
        /// </summary>
        ModifySkill = 17,
        /// <summary>
        /// 标记伤害：例如Arthur1技能
        /// </summary>
        ArthurMark = 18,
        /// <summary>
        /// 目标闪现跳跃：例如Arthur1技能
        /// </summary>
        TargetFlashMove = 19,
        /// <summary>
        /// 方向闪现跳跃：例如Arthur1技能
        /// </summary>
        DirectionFlashMove = 20,
        /// <summary>
        /// 百分比生命伤害：例如Arthur1技能
        /// </summary>
        ExecuteDamage = 21,
        /// <summary>
        /// 主动技能修改：例如Houyi
        /// </summary>
        HouyiActiveSkillModify = 22,
        /// <summary>
        /// 强化普攻为散射：例如Houyi
        /// </summary>
        Scatter = 23,
        /// <summary>
        /// 被动攻速加成：例如Houyi
        /// </summary>
        HouyiPasvAttackSpeed = 24,
        /// <summary>
        /// 被动技能修改：例如Houyi
        /// </summary>
        HouyiPasvSkillModify = 25,
        /// <summary>
        /// 被动技能多重射击：例如Houyi
        /// </summary>
        HouyiPasvMultiArrow = 26,
        /// <summary>
        /// 混合多重射击与散射：例如Houyi
        /// </summary>
        HouyiMixedMultiScatter = 27,
        /// <summary>
        /// Jinx大招混合：计距、百分比、爆炸溅射
        /// </summary>
        JinxRocketMixed_DynamicGroup = 28,
        /// <summary>
        /// 被动类buff：不可叠加的击杀速度加成
        /// </summary>
        NSSpeedUpPasv = 29,
    }
}
