//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg
{
    /// <summary>
    /// 子弹寻找目标模式
    /// </summary>
    public enum BulletTypeEnum
    {
        /// <summary>
        /// ui指定方向
        /// </summary>
        UIDirection = 0,
        /// <summary>
        /// ui指定位置
        /// </summary>
        UIPosition = 1,
        /// <summary>
        /// 当前技能目标
        /// </summary>
        SkillTarget = 2,
        /// <summary>
        /// 根据Buff计算
        /// </summary>
        BuffSearch = 3,
    }
}
