//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg
{

public sealed partial class CommonModifySkillBuffCfg :  BuffCfg 
{
    public CommonModifySkillBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        originalID = _buf.ReadInt();
        replaceID = _buf.ReadInt();
        times = _buf.ReadInt();
        replaceIconId = _buf.ReadInt();
        PostInit();
    }

    public static CommonModifySkillBuffCfg DeserializeCommonModifySkillBuffCfg(ByteBuf _buf)
    {
        return new CommonModifySkillBuffCfg(_buf);
    }

    public int originalID { get; private set; }
    public int replaceID { get; private set; }
    /// <summary>
    /// 执行回数，-1就是永久生效
    /// </summary>
    public int times { get; private set; }
    /// <summary>
    /// 替换刷新本地技能位置（0普攻，1-3技能）
    /// </summary>
    public int replaceIconId { get; private set; }

    public const int __ID__ = 455491269;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "buffId:" + buffId + ","
        + "buffName:" + buffName + ","
        + "buffType:" + buffType + ","
        + "attacher:" + attacher + ","
        + "staticPosType:" + staticPosType + ","
        + "impacter:" + impacter + ","
        + "buffDelay:" + buffDelay + ","
        + "buffInterval:" + buffInterval + ","
        + "buffDuration:" + buffDuration + ","
        + "buffAudio:" + buffAudio + ","
        + "buffEffect:" + buffEffect + ","
        + "hitTickAudio:" + hitTickAudio + ","
        + "effectDestoryExtend:" + effectDestoryExtend + ","
        + "originalID:" + originalID + ","
        + "replaceID:" + replaceID + ","
        + "times:" + times + ","
        + "replaceIconId:" + replaceIconId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
