//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg
{

/// <summary>
/// 碰撞关系配置
/// </summary>
public sealed partial class TargetCfg :  Bright.Config.BeanBase 
{
    public TargetCfg(ByteBuf _buf) 
    {
        targetTeam = (TargetTeamEnum)_buf.ReadInt();
        selectRule = (SelectRuleEnum)_buf.ReadInt();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);targetTypeArr = new UnitTypeEnum[n];for(var i = 0 ; i < n ; i++) { UnitTypeEnum _e;_e = (UnitTypeEnum)_buf.ReadInt(); targetTypeArr[i] = _e;}}
        selectRange = _buf.ReadFloat();
        searchDis = _buf.ReadFloat();
        PostInit();
    }

    public static TargetCfg DeserializeTargetCfg(ByteBuf _buf)
    {
        return new TargetCfg(_buf);
    }

    public TargetTeamEnum targetTeam { get; private set; }
    public SelectRuleEnum selectRule { get; private set; }
    /// <summary>
    /// 可以是多类目标：英雄、小兵、塔
    /// </summary>
    public UnitTypeEnum[] targetTypeArr { get; private set; }
    /// <summary>
    /// 查找目标范围距离
    /// </summary>
    public float selectRange { get; private set; }
    /// <summary>
    /// 移动攻击搜索距离 m
    /// </summary>
    public float searchDis { get; private set; }

    public const int __ID__ = 1188364531;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "targetTeam:" + targetTeam + ","
        + "selectRule:" + selectRule + ","
        + "targetTypeArr:" + Bright.Common.StringUtil.CollectionToString(targetTypeArr) + ","
        + "selectRange:" + selectRange + ","
        + "searchDis:" + searchDis + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
