//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg
{
    /// <summary>
    /// 单位类型
    /// </summary>
    public enum UnitTypeEnum
    {
        /// <summary>
        /// 英雄
        /// </summary>
        Hero = 0,
        /// <summary>
        /// 小兵
        /// </summary>
        Soldier = 1,
        /// <summary>
        /// 防御塔
        /// </summary>
        Tower = 2,
        /// <summary>
        /// 水晶
        /// </summary>
        Crystal = 3,
    }
}
