//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Datas
{
   
public partial class TbBuffCfg
{
    private readonly Dictionary<int, BuffCfg> _dataMap;
    private readonly List<BuffCfg> _dataList;
    
    public TbBuffCfg(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, BuffCfg>();
        _dataList = new List<BuffCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            BuffCfg _v;
            _v = BuffCfg.DeserializeBuffCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.buffId, _v);
        }
        PostInit();
    }

    public Dictionary<int, BuffCfg> DataMap => _dataMap;
    public List<BuffCfg> DataList => _dataList;

    public T GetOrDefaultAs<T>(int key) where T : BuffCfg => _dataMap.TryGetValue(key, out var v) ? (T)v : null;
    public T GetAs<T>(int key) where T : BuffCfg => (T)_dataMap[key];
    public BuffCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuffCfg Get(int key) => _dataMap[key];
    public BuffCfg this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}