//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Datas
{
   
public partial class TbHouyiScatterArrowBuffCfg
{
    private readonly Dictionary<int, HouyiScatterArrowBuffCfg> _dataMap;
    private readonly List<HouyiScatterArrowBuffCfg> _dataList;
    
    public TbHouyiScatterArrowBuffCfg(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, HouyiScatterArrowBuffCfg>();
        _dataList = new List<HouyiScatterArrowBuffCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            HouyiScatterArrowBuffCfg _v;
            _v = HouyiScatterArrowBuffCfg.DeserializeHouyiScatterArrowBuffCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.buffId, _v);
        }
        PostInit();
    }

    public Dictionary<int, HouyiScatterArrowBuffCfg> DataMap => _dataMap;
    public List<HouyiScatterArrowBuffCfg> DataList => _dataList;

    public HouyiScatterArrowBuffCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HouyiScatterArrowBuffCfg Get(int key) => _dataMap[key];
    public HouyiScatterArrowBuffCfg this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}