//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Datas
{
   
public partial class TbHouyiMultipleSkillModifyBuffCfg
{
    private readonly Dictionary<int, HouyiMultipleSkillModifyBuffCfg> _dataMap;
    private readonly List<HouyiMultipleSkillModifyBuffCfg> _dataList;
    
    public TbHouyiMultipleSkillModifyBuffCfg(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, HouyiMultipleSkillModifyBuffCfg>();
        _dataList = new List<HouyiMultipleSkillModifyBuffCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            HouyiMultipleSkillModifyBuffCfg _v;
            _v = HouyiMultipleSkillModifyBuffCfg.DeserializeHouyiMultipleSkillModifyBuffCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.buffId, _v);
        }
        PostInit();
    }

    public Dictionary<int, HouyiMultipleSkillModifyBuffCfg> DataMap => _dataMap;
    public List<HouyiMultipleSkillModifyBuffCfg> DataList => _dataList;

    public HouyiMultipleSkillModifyBuffCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HouyiMultipleSkillModifyBuffCfg Get(int key) => _dataMap[key];
    public HouyiMultipleSkillModifyBuffCfg this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}