//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Datas
{
   
public partial class TbJinxRocketMixedBuffCfg_DynamicGroup
{
    private readonly Dictionary<int, JinxRocketMixedBuffCfg_DynamicGroup> _dataMap;
    private readonly List<JinxRocketMixedBuffCfg_DynamicGroup> _dataList;
    
    public TbJinxRocketMixedBuffCfg_DynamicGroup(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, JinxRocketMixedBuffCfg_DynamicGroup>();
        _dataList = new List<JinxRocketMixedBuffCfg_DynamicGroup>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            JinxRocketMixedBuffCfg_DynamicGroup _v;
            _v = JinxRocketMixedBuffCfg_DynamicGroup.DeserializeJinxRocketMixedBuffCfg_DynamicGroup(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.buffId, _v);
        }
        PostInit();
    }

    public Dictionary<int, JinxRocketMixedBuffCfg_DynamicGroup> DataMap => _dataMap;
    public List<JinxRocketMixedBuffCfg_DynamicGroup> DataList => _dataList;

    public JinxRocketMixedBuffCfg_DynamicGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public JinxRocketMixedBuffCfg_DynamicGroup Get(int key) => _dataMap[key];
    public JinxRocketMixedBuffCfg_DynamicGroup this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}