//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Datas
{
   
public partial class TbNormalBuffCfg
{
    private readonly Dictionary<int, NormalBuffCfg> _dataMap;
    private readonly List<NormalBuffCfg> _dataList;
    
    public TbNormalBuffCfg(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, NormalBuffCfg>();
        _dataList = new List<NormalBuffCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            NormalBuffCfg _v;
            _v = NormalBuffCfg.DeserializeNormalBuffCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.buffId, _v);
        }
        PostInit();
    }

    public Dictionary<int, NormalBuffCfg> DataMap => _dataMap;
    public List<NormalBuffCfg> DataList => _dataList;

    public NormalBuffCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public NormalBuffCfg Get(int key) => _dataMap[key];
    public NormalBuffCfg this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}