//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Datas
{
   
public partial class TbStunBuffCfg_DynamicTime
{
    private readonly Dictionary<int, StunBuffCfg_DynamicTime> _dataMap;
    private readonly List<StunBuffCfg_DynamicTime> _dataList;
    
    public TbStunBuffCfg_DynamicTime(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, StunBuffCfg_DynamicTime>();
        _dataList = new List<StunBuffCfg_DynamicTime>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            StunBuffCfg_DynamicTime _v;
            _v = StunBuffCfg_DynamicTime.DeserializeStunBuffCfg_DynamicTime(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.buffId, _v);
        }
        PostInit();
    }

    public Dictionary<int, StunBuffCfg_DynamicTime> DataMap => _dataMap;
    public List<StunBuffCfg_DynamicTime> DataList => _dataList;

    public StunBuffCfg_DynamicTime GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StunBuffCfg_DynamicTime Get(int key) => _dataMap[key];
    public StunBuffCfg_DynamicTime this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}