//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Datas
{
   
public partial class TbUnitInfoCfg
{
    private readonly Dictionary<int, UnitInfoCfg> _dataMap;
    private readonly List<UnitInfoCfg> _dataList;
    
    public TbUnitInfoCfg(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, UnitInfoCfg>();
        _dataList = new List<UnitInfoCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UnitInfoCfg _v;
            _v = UnitInfoCfg.DeserializeUnitInfoCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.unitId, _v);
        }
        PostInit();
    }

    public Dictionary<int, UnitInfoCfg> DataMap => _dataMap;
    public List<UnitInfoCfg> DataList => _dataList;

    public UnitInfoCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UnitInfoCfg Get(int key) => _dataMap[key];
    public UnitInfoCfg this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}