//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Sirenix.OdinInspector;



namespace editor.cfg
{

    [Serializable]
public sealed partial class BulletCfg :  Bright.Config.EditorBeanBase 
{
    public BulletCfg()
    {
            bulletType = "UIDirection";
            bulletName = "";
            resPath = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["bulletType"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  bulletType = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["bulletName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  bulletName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["resPath"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  resPath = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["bulletSpeed"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  bulletSpeed = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["bulletSize"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  bulletSize = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["bulletHeight"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  bulletHeight = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["bulletOffset"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  bulletOffset = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["bulletDelay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  bulletDelay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["canBlock"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsBoolean) { throw new SerializationException(); }  canBlock = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["impacter"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsObject) { throw new SerializationException(); }  impacter = TargetCfg.LoadJsonTargetCfg(_fieldJson);
            }
        }
        
        { 
            var _fieldJson = _json["bulletDuration"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  bulletDuration = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {        
        {
            _json["bulletType"] = new JSONString(bulletType);
        }
        {

            if (bulletName == null) { throw new System.ArgumentNullException(); }
            _json["bulletName"] = new JSONString(bulletName);
        }
        {

            if (resPath == null) { throw new System.ArgumentNullException(); }
            _json["resPath"] = new JSONString(resPath);
        }
        {
            _json["bulletSpeed"] = new JSONNumber(bulletSpeed);
        }
        {
            _json["bulletSize"] = new JSONNumber(bulletSize);
        }
        {
            _json["bulletHeight"] = new JSONNumber(bulletHeight);
        }
        {
            _json["bulletOffset"] = new JSONNumber(bulletOffset);
        }
        {
            _json["bulletDelay"] = new JSONNumber(bulletDelay);
        }
        {
            _json["canBlock"] = new JSONBool(canBlock);
        }

        if (impacter != null)
        {
            { var __bjson = new JSONObject();  TargetCfg.SaveJsonTargetCfg(impacter, __bjson); _json["impacter"] = __bjson; }
        }
        {
            _json["bulletDuration"] = new JSONNumber(bulletDuration);
        }
    }

    public static BulletCfg LoadJsonBulletCfg(SimpleJSON.JSONNode _json)
    {
        BulletCfg obj = new BulletCfg();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonBulletCfg(BulletCfg _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    [ShowInInspector][ValueDropdown("BulletTypeEnum_List")]public string bulletType { get; set; }
    private static System.Collections.IEnumerable BulletTypeEnum_List = JsonEnumHelper.BulletTypeEnum_List;

    [ShowInInspector]public string bulletName { get; set; }

    [ShowInInspector]public string resPath { get; set; }

    [ShowInInspector]public float bulletSpeed { get; set; }

    [ShowInInspector]public float bulletSize { get; set; }

    [ShowInInspector]public float bulletHeight { get; set; }

    /// <summary>
    /// 发射子弹的时候，要往发射方向偏移一小段而不是从中心
    /// </summary>
    [ShowInInspector]public float bulletOffset { get; set; }

    [ShowInInspector]public int bulletDelay { get; set; }

    [ShowInInspector]public bool canBlock { get; set; }

    [ShowInInspector]public TargetCfg impacter { get; set; }

    [ShowInInspector]public int bulletDuration { get; set; }

}
}
