//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Sirenix.OdinInspector;


namespace editor.cfg
{
    [Serializable]
public sealed partial class HouyiPasvAttackSpeedBuffCfg :  BuffCfg 
{
    public HouyiPasvAttackSpeedBuffCfg()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        base.LoadJson(_json);
        { 
            var _fieldJson = _json["overCount"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  overCount = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["speedAddtion"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  speedAddtion = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["resetTime"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  resetTime = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {        
        base.SaveJson(_json);
        {
            _json["overCount"] = new JSONNumber(overCount);
        }
        {
            _json["speedAddtion"] = new JSONNumber(speedAddtion);
        }
        {
            _json["resetTime"] = new JSONNumber(resetTime);
        }
    }

    public static HouyiPasvAttackSpeedBuffCfg LoadJsonHouyiPasvAttackSpeedBuffCfg(SimpleJSON.JSONNode _json)
    {
        HouyiPasvAttackSpeedBuffCfg obj = new HouyiPasvAttackSpeedBuffCfg();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonHouyiPasvAttackSpeedBuffCfg(HouyiPasvAttackSpeedBuffCfg _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 叠加层数
    /// </summary>
    [ShowInInspector, VerticalGroup("特殊")]public int overCount { get; set; }

    /// <summary>
    /// 加成百分比
    /// </summary>
    [ShowInInspector, VerticalGroup("特殊")]public int speedAddtion { get; set; }

    /// <summary>
    /// 重置周期
    /// </summary>
    [ShowInInspector, VerticalGroup("特殊")]public int resetTime { get; set; }

}
}
