//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Sirenix.OdinInspector;


namespace editor.cfg
{
    [Serializable]
public sealed partial class HPCureBuffCfg :  BuffCfg 
{
    public HPCureBuffCfg()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        base.LoadJson(_json);
        { 
            var _fieldJson = _json["cureHPpct"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  cureHPpct = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {        
        base.SaveJson(_json);
        {
            _json["cureHPpct"] = new JSONNumber(cureHPpct);
        }
    }

    public static HPCureBuffCfg LoadJsonHPCureBuffCfg(SimpleJSON.JSONNode _json)
    {
        HPCureBuffCfg obj = new HPCureBuffCfg();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonHPCureBuffCfg(HPCureBuffCfg _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 治疗Hp百分比
    /// </summary>
    [ShowInInspector, VerticalGroup("特殊")]public int cureHPpct { get; set; }

}
}
