//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace editor.cfg
{
    /// <summary>
    /// buff位置确定方式
    /// </summary>
    public static partial class StaticPosTypeEnum
    {
        public static readonly Bright.Config.EditorEnumItemInfo None = new Bright.Config.EditorEnumItemInfo("None", "", 0, "无");
        public static readonly Bright.Config.EditorEnumItemInfo SkillCasterPos = new Bright.Config.EditorEnumItemInfo("SkillCasterPos", "", 1, "Buff所属技能施放者的位置");
        public static readonly Bright.Config.EditorEnumItemInfo SkillLockTargetPos = new Bright.Config.EditorEnumItemInfo("SkillLockTargetPos", "", 2, "Buff所属技能锁定目标的位置");
        public static readonly Bright.Config.EditorEnumItemInfo BulletHitTargetPos = new Bright.Config.EditorEnumItemInfo("BulletHitTargetPos", "", 3, "子弹命中目标的位置");
        public static readonly Bright.Config.EditorEnumItemInfo UIInputPos = new Bright.Config.EditorEnumItemInfo("UIInputPos", "", 4, "UI输入位置信息，比如后裔2技能");

        private static readonly System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo>
        {
            None,
            SkillCasterPos,
            SkillLockTargetPos,
            BulletHitTargetPos,
            UIInputPos,
        };

        public static System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> GetItems() => __items;

        public static Bright.Config.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }
}
