//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace editor.cfg
{
    /// <summary>
    /// 作用目标队伍
    /// </summary>
    public static partial class TargetTeamEnum
    {
        public static readonly Bright.Config.EditorEnumItemInfo Dynamic = new Bright.Config.EditorEnumItemInfo("Dynamic", "", 0, "动态");
        public static readonly Bright.Config.EditorEnumItemInfo Friend = new Bright.Config.EditorEnumItemInfo("Friend", "", 1, "友军");
        public static readonly Bright.Config.EditorEnumItemInfo Enemy = new Bright.Config.EditorEnumItemInfo("Enemy", "", 2, "敌军");

        private static readonly System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo>
        {
            Dynamic,
            Friend,
            Enemy,
        };

        public static System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> GetItems() => __items;

        public static Bright.Config.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }
}
