//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace editor.cfg
{
    /// <summary>
    /// 单位类型
    /// </summary>
    public static partial class UnitTypeEnum
    {
        public static readonly Bright.Config.EditorEnumItemInfo Hero = new Bright.Config.EditorEnumItemInfo("Hero", "", 0, "英雄");
        public static readonly Bright.Config.EditorEnumItemInfo Soldier = new Bright.Config.EditorEnumItemInfo("Soldier", "", 1, "小兵");
        public static readonly Bright.Config.EditorEnumItemInfo Tower = new Bright.Config.EditorEnumItemInfo("Tower", "", 2, "防御塔");
        public static readonly Bright.Config.EditorEnumItemInfo Crystal = new Bright.Config.EditorEnumItemInfo("Crystal", "", 3, "水晶");

        private static readonly System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo>
        {
            Hero,
            Soldier,
            Tower,
            Crystal,
        };

        public static System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> GetItems() => __items;

        public static Bright.Config.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }
}
