//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Datas
{
   
public partial class TbDamageBuffCfg_DynamicGroup
{
    private readonly Dictionary<int, DamageBuffCfg_DynamicGroup> _dataMap;
    private readonly List<DamageBuffCfg_DynamicGroup> _dataList;
    
    public TbDamageBuffCfg_DynamicGroup(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, DamageBuffCfg_DynamicGroup>();
        _dataList = new List<DamageBuffCfg_DynamicGroup>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DamageBuffCfg_DynamicGroup _v;
            _v = DamageBuffCfg_DynamicGroup.DeserializeDamageBuffCfg_DynamicGroup(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.buffId, _v);
        }
        PostInit();
    }

    public Dictionary<int, DamageBuffCfg_DynamicGroup> DataMap => _dataMap;
    public List<DamageBuffCfg_DynamicGroup> DataList => _dataList;

    public DamageBuffCfg_DynamicGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DamageBuffCfg_DynamicGroup Get(int key) => _dataMap[key];
    public DamageBuffCfg_DynamicGroup this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}