//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Datas
{
   
public partial class TbSkillCfg
{
    private readonly Dictionary<int, SkillCfg> _dataMap;
    private readonly List<SkillCfg> _dataList;
    
    public TbSkillCfg(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, SkillCfg>();
        _dataList = new List<SkillCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SkillCfg _v;
            _v = SkillCfg.DeserializeSkillCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.skillId, _v);
        }
        PostInit();
    }

    public Dictionary<int, SkillCfg> DataMap => _dataMap;
    public List<SkillCfg> DataList => _dataList;

    public SkillCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SkillCfg Get(int key) => _dataMap[key];
    public SkillCfg this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}