//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg
{
    /// <summary>
    /// buff附着目标
    /// </summary>
    public enum AttachTypeEnum
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 由施术者自己确定：给自己，例如Arthur的1技能加速buff
        /// </summary>
        Caster = 1,
        /// <summary>
        /// 由施术者自己确定：区域，例如Arthur大招(位置固定)产生的持续范围伤害
        /// </summary>
        Indie = 2,
        /// <summary>
        /// 由受击者确定：给目标，例如Arthur的1技能沉默buff
        /// </summary>
        Target = 3,
        /// <summary>
        /// 由受击者确定：例如Houyi大招命中(位置动态)目标时产生的范围伤害
        /// </summary>
        Bullet = 4,
    }
}
