//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg
{

public sealed partial class HouyiScatterSkillModifyBuffCfg :  BuffCfg 
{
    public HouyiScatterSkillModifyBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        originalID = _buf.ReadInt();
        powerID = _buf.ReadInt();
        superPowerID = _buf.ReadInt();
        PostInit();
    }

    public static HouyiScatterSkillModifyBuffCfg DeserializeHouyiScatterSkillModifyBuffCfg(ByteBuf _buf)
    {
        return new HouyiScatterSkillModifyBuffCfg(_buf);
    }

    public int originalID { get; private set; }
    public int powerID { get; private set; }
    public int superPowerID { get; private set; }

    public const int __ID__ = 1216890726;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "buffId:" + buffId + ","
        + "buffName:" + buffName + ","
        + "buffType:" + buffType + ","
        + "attacher:" + attacher + ","
        + "staticPosType:" + staticPosType + ","
        + "impacter:" + impacter + ","
        + "buffDelay:" + buffDelay + ","
        + "buffInterval:" + buffInterval + ","
        + "buffDuration:" + buffDuration + ","
        + "buffAudio:" + buffAudio + ","
        + "buffEffect:" + buffEffect + ","
        + "hitTickAudio:" + hitTickAudio + ","
        + "originalID:" + originalID + ","
        + "powerID:" + powerID + ","
        + "superPowerID:" + superPowerID + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
