//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg
{

public sealed partial class HouyiPasvAttackSpeedBuffCfg :  BuffCfg 
{
    public HouyiPasvAttackSpeedBuffCfg(ByteBuf _buf)  : base(_buf) 
    {
        overCount = _buf.ReadInt();
        speedAddtion = _buf.ReadInt();
        resetTime = _buf.ReadInt();
        PostInit();
    }

    public static HouyiPasvAttackSpeedBuffCfg DeserializeHouyiPasvAttackSpeedBuffCfg(ByteBuf _buf)
    {
        return new HouyiPasvAttackSpeedBuffCfg(_buf);
    }

    /// <summary>
    /// 叠加层数
    /// </summary>
    public int overCount { get; private set; }
    /// <summary>
    /// 加成百分比
    /// </summary>
    public int speedAddtion { get; private set; }
    /// <summary>
    /// 重置周期
    /// </summary>
    public int resetTime { get; private set; }

    public const int __ID__ = -732473404;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "buffId:" + buffId + ","
        + "buffName:" + buffName + ","
        + "buffType:" + buffType + ","
        + "attacher:" + attacher + ","
        + "staticPosType:" + staticPosType + ","
        + "impacter:" + impacter + ","
        + "buffDelay:" + buffDelay + ","
        + "buffInterval:" + buffInterval + ","
        + "buffDuration:" + buffDuration + ","
        + "buffAudio:" + buffAudio + ","
        + "buffEffect:" + buffEffect + ","
        + "hitTickAudio:" + hitTickAudio + ","
        + "overCount:" + overCount + ","
        + "speedAddtion:" + speedAddtion + ","
        + "resetTime:" + resetTime + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
