//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg
{
    /// <summary>
    /// 技能释放模式
    /// </summary>
    public enum ReleaseModeEnum
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 点击直接释放
        /// </summary>
        Click = 1,
        /// <summary>
        /// 根据位置释放
        /// </summary>
        Position = 2,
        /// <summary>
        /// 根据方向释放
        /// </summary>
        Direction = 3,
    }
}
