//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg
{
    /// <summary>
    /// 目标选择规则
    /// </summary>
    public enum SelectRuleEnum
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 单体血量最小
        /// </summary>
        MinHpValue = 1,
        /// <summary>
        /// 单体血量百分比最小
        /// </summary>
        MinHpPercent = 2,
        /// <summary>
        /// 最近的单个
        /// </summary>
        TargetClosestSingle = 3,
        /// <summary>
        /// 靠近某个位置的单个选择
        /// </summary>
        PositionClosestSingle = 4,
        /// <summary>
        /// 最近的多个（范围选择）
        /// </summary>
        TargetClosestMulti = 5,
        /// <summary>
        /// 靠近某个位置的多个选择（范围选择）
        /// </summary>
        PositionClosestMulti = 6,
        /// <summary>
        /// 所有英雄单位
        /// </summary>
        Hero = 7,
    }
}
