//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg
{
    /// <summary>
    /// buff位置确定方式
    /// </summary>
    public enum StaticPosTypeEnum
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// Buff所属技能施放者的位置
        /// </summary>
        SkillCasterPos = 1,
        /// <summary>
        /// Buff所属技能锁定目标的位置
        /// </summary>
        SkillLockTargetPos = 2,
        /// <summary>
        /// 子弹命中目标的位置
        /// </summary>
        BulletHitTargetPos = 3,
        /// <summary>
        /// UI输入位置信息，比如后裔2技能
        /// </summary>
        UIInputPos = 4,
    }
}
