//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg
{
    /// <summary>
    /// 作用目标队伍
    /// </summary>
    public enum TargetTeamEnum
    {
        /// <summary>
        /// 动态
        /// </summary>
        Dynamic = 0,
        /// <summary>
        /// 友军
        /// </summary>
        Friend = 1,
        /// <summary>
        /// 敌军
        /// </summary>
        Enemy = 2,
    }
}
