//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace editor.cfg
{
    /// <summary>
    /// buff类型，用来创建不同类型的buff
    /// </summary>
    public static partial class BuffTypeEnum
    {
        public static readonly Bright.Config.EditorEnumItemInfo None = new Bright.Config.EditorEnumItemInfo("None", "", 0, "");
        public static readonly Bright.Config.EditorEnumItemInfo HPCure = new Bright.Config.EditorEnumItemInfo("HPCure", "", 1, "治疗");
        public static readonly Bright.Config.EditorEnumItemInfo ModifySkill = new Bright.Config.EditorEnumItemInfo("ModifySkill", "", 2, "");
        public static readonly Bright.Config.EditorEnumItemInfo MoveSpeed_Single = new Bright.Config.EditorEnumItemInfo("MoveSpeed_Single", "", 3, "单体加速buff");
        public static readonly Bright.Config.EditorEnumItemInfo ArthurMark = new Bright.Config.EditorEnumItemInfo("ArthurMark", "", 4, "Arthur1技能的标记伤害Buff");
        public static readonly Bright.Config.EditorEnumItemInfo Silense = new Bright.Config.EditorEnumItemInfo("Silense", "", 5, "沉默");
        public static readonly Bright.Config.EditorEnumItemInfo TargetFlashMove = new Bright.Config.EditorEnumItemInfo("TargetFlashMove", "", 6, "");
        public static readonly Bright.Config.EditorEnumItemInfo DirectionFlashMove = new Bright.Config.EditorEnumItemInfo("DirectionFlashMove", "", 7, "");
        public static readonly Bright.Config.EditorEnumItemInfo ExecuteDamage = new Bright.Config.EditorEnumItemInfo("ExecuteDamage", "", 8, "");
        public static readonly Bright.Config.EditorEnumItemInfo Knockup_Group = new Bright.Config.EditorEnumItemInfo("Knockup_Group", "", 9, "群体击飞");
        public static readonly Bright.Config.EditorEnumItemInfo Stun_Single_DynamicTime = new Bright.Config.EditorEnumItemInfo("Stun_Single_DynamicTime", "", 10, "");
        public static readonly Bright.Config.EditorEnumItemInfo HouyiActiveSkillModify = new Bright.Config.EditorEnumItemInfo("HouyiActiveSkillModify", "", 11, "Houyi主动技能修改buff");
        public static readonly Bright.Config.EditorEnumItemInfo Scatter = new Bright.Config.EditorEnumItemInfo("Scatter", "", 12, "");
        public static readonly Bright.Config.EditorEnumItemInfo HouyiPasvAttackSpeed = new Bright.Config.EditorEnumItemInfo("HouyiPasvAttackSpeed", "", 13, "Houyi被动攻速加成buff");
        public static readonly Bright.Config.EditorEnumItemInfo HouyiPasvSkillModify = new Bright.Config.EditorEnumItemInfo("HouyiPasvSkillModify", "", 14, "Houyi被动技能修改Buff");
        public static readonly Bright.Config.EditorEnumItemInfo HouyiPasvMultiArrow = new Bright.Config.EditorEnumItemInfo("HouyiPasvMultiArrow", "", 15, "Houyi被动技能多重射击Buff");
        public static readonly Bright.Config.EditorEnumItemInfo HouyiMixedMultiScatter = new Bright.Config.EditorEnumItemInfo("HouyiMixedMultiScatter", "", 16, "混合多重射击与散射");
        public static readonly Bright.Config.EditorEnumItemInfo MoveSpeed_DynamicGroup = new Bright.Config.EditorEnumItemInfo("MoveSpeed_DynamicGroup", "", 17, "动态群体移速Buff");
        public static readonly Bright.Config.EditorEnumItemInfo MoveSpeed_StaticGroup = new Bright.Config.EditorEnumItemInfo("MoveSpeed_StaticGroup", "", 18, "静态群体移速buff");
        public static readonly Bright.Config.EditorEnumItemInfo Damage_DynamicGroup = new Bright.Config.EditorEnumItemInfo("Damage_DynamicGroup", "", 19, "动态群体伤害");
        public static readonly Bright.Config.EditorEnumItemInfo Damage_StaticGroup = new Bright.Config.EditorEnumItemInfo("Damage_StaticGroup", "", 20, "");
        public static readonly Bright.Config.EditorEnumItemInfo MoveAttack = new Bright.Config.EditorEnumItemInfo("MoveAttack", "", 21, "移动攻击");

        private static readonly System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo>
        {
            None,
            HPCure,
            ModifySkill,
            MoveSpeed_Single,
            ArthurMark,
            Silense,
            TargetFlashMove,
            DirectionFlashMove,
            ExecuteDamage,
            Knockup_Group,
            Stun_Single_DynamicTime,
            HouyiActiveSkillModify,
            Scatter,
            HouyiPasvAttackSpeed,
            HouyiPasvSkillModify,
            HouyiPasvMultiArrow,
            HouyiMixedMultiScatter,
            MoveSpeed_DynamicGroup,
            MoveSpeed_StaticGroup,
            Damage_DynamicGroup,
            Damage_StaticGroup,
            MoveAttack,
        };

        public static System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> GetItems() => __items;

        public static Bright.Config.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }
}
