//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Sirenix.OdinInspector;


namespace editor.cfg
{
[Serializable]
public sealed partial class CommonModifySkillBuffCfg :  BuffCfg 
{
    public CommonModifySkillBuffCfg()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        base.LoadJson(_json);
        { 
            var _fieldJson = _json["originalID"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  originalID = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["replaceID"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  replaceID = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["times"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  times = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["replaceIconId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  replaceIconId = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {        
        base.SaveJson(_json);
        {
            _json["originalID"] = new JSONNumber(originalID);
        }
        {
            _json["replaceID"] = new JSONNumber(replaceID);
        }
        {
            _json["times"] = new JSONNumber(times);
        }
        {
            _json["replaceIconId"] = new JSONNumber(replaceIconId);
        }
    }

    public static CommonModifySkillBuffCfg LoadJsonCommonModifySkillBuffCfg(SimpleJSON.JSONNode _json)
    {
        CommonModifySkillBuffCfg obj = new CommonModifySkillBuffCfg();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonCommonModifySkillBuffCfg(CommonModifySkillBuffCfg _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    [ShowInInspector]public int originalID { get; set; }

    [ShowInInspector]public int replaceID { get; set; }

    /// <summary>
    /// 执行回数，-1就是永久生效
    /// </summary>
    [ShowInInspector]public int times { get; set; }

    /// <summary>
    /// 替换刷新本地技能位置（0普攻，1-3技能）
    /// </summary>
    [ShowInInspector]public int replaceIconId { get; set; }

}
}
