//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Sirenix.OdinInspector;


namespace editor.cfg
{
    [Serializable]
public sealed partial class HouyiMixedMultiScatterBuffCfg :  BuffCfg 
{
    public HouyiMixedMultiScatterBuffCfg()
    {
            targetCfg = new TargetCfg();
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        base.LoadJson(_json);
        { 
            var _fieldJson = _json["scatterCount"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  scatterCount = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["targetCfg"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsObject) { throw new SerializationException(); }  targetCfg = TargetCfg.LoadJsonTargetCfg(_fieldJson);
            }
        }
        
        { 
            var _fieldJson = _json["damagePct"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  damagePct = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["arrowCount"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  arrowCount = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["arrowDelay"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  arrowDelay = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["posOffset"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  posOffset = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {        
        base.SaveJson(_json);
        {
            _json["scatterCount"] = new JSONNumber(scatterCount);
        }
        {

            if (targetCfg == null) { throw new System.ArgumentNullException(); }
            { var __bjson = new JSONObject();  TargetCfg.SaveJsonTargetCfg(targetCfg, __bjson); _json["targetCfg"] = __bjson; }
        }
        {
            _json["damagePct"] = new JSONNumber(damagePct);
        }
        {
            _json["arrowCount"] = new JSONNumber(arrowCount);
        }
        {
            _json["arrowDelay"] = new JSONNumber(arrowDelay);
        }
        {
            _json["posOffset"] = new JSONNumber(posOffset);
        }
    }

    public static HouyiMixedMultiScatterBuffCfg LoadJsonHouyiMixedMultiScatterBuffCfg(SimpleJSON.JSONNode _json)
    {
        HouyiMixedMultiScatterBuffCfg obj = new HouyiMixedMultiScatterBuffCfg();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonHouyiMixedMultiScatterBuffCfg(HouyiMixedMultiScatterBuffCfg _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 散射个数
    /// </summary>
    [ShowInInspector, VerticalGroup("特殊")]public int scatterCount { get; set; }

    /// <summary>
    /// 散射目标查找规则
    /// </summary>
    [ShowInInspector, VerticalGroup("特殊")]public TargetCfg targetCfg { get; set; }

    /// <summary>
    /// 散射子弹伤害百分比
    /// </summary>
    [ShowInInspector, VerticalGroup("特殊")]public int damagePct { get; set; }

    [ShowInInspector, VerticalGroup("特殊")]public int arrowCount { get; set; }

    [ShowInInspector, VerticalGroup("特殊")]public int arrowDelay { get; set; }

    [ShowInInspector, VerticalGroup("特殊")]public float posOffset { get; set; }

}
}
