//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace editor.cfg
{
    /// <summary>
    /// 目标选择规则
    /// </summary>
    public static partial class SelectRuleEnum
    {
        public static readonly Bright.Config.EditorEnumItemInfo None = new Bright.Config.EditorEnumItemInfo("None", "", 0, "无");
        public static readonly Bright.Config.EditorEnumItemInfo MinHpValue = new Bright.Config.EditorEnumItemInfo("MinHpValue", "", 1, "单体血量最小");
        public static readonly Bright.Config.EditorEnumItemInfo MinHpPercent = new Bright.Config.EditorEnumItemInfo("MinHpPercent", "", 2, "单体血量百分比最小");
        public static readonly Bright.Config.EditorEnumItemInfo TargetClosestSingle = new Bright.Config.EditorEnumItemInfo("TargetClosestSingle", "", 3, "最近的单个");
        public static readonly Bright.Config.EditorEnumItemInfo PositionClosestSingle = new Bright.Config.EditorEnumItemInfo("PositionClosestSingle", "", 4, "靠近某个位置的单个选择");
        public static readonly Bright.Config.EditorEnumItemInfo TargetClosestMulti = new Bright.Config.EditorEnumItemInfo("TargetClosestMulti", "", 5, "最近的多个（范围选择）");
        public static readonly Bright.Config.EditorEnumItemInfo PositionClosestMulti = new Bright.Config.EditorEnumItemInfo("PositionClosestMulti", "", 6, "靠近某个位置的多个选择（范围选择）");
        public static readonly Bright.Config.EditorEnumItemInfo Hero = new Bright.Config.EditorEnumItemInfo("Hero", "", 7, "所有英雄单位");

        private static readonly System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo>
        {
            None,
            MinHpValue,
            MinHpPercent,
            TargetClosestSingle,
            PositionClosestSingle,
            TargetClosestMulti,
            PositionClosestMulti,
            Hero,
        };

        public static System.Collections.Generic.List<Bright.Config.EditorEnumItemInfo> GetItems() => __items;

        public static Bright.Config.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Bright.Config.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }
}
