//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using Sirenix.OdinInspector;


namespace editor.cfg
{
    [Serializable]
public sealed partial class TargetFlashMoveBuffCfg :  BuffCfg 
{
    public TargetFlashMoveBuffCfg()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        base.LoadJson(_json);
        { 
            var _fieldJson = _json["offset"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  offset = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {        
        base.SaveJson(_json);
        {
            _json["offset"] = new JSONNumber(offset);
        }
    }

    public static TargetFlashMoveBuffCfg LoadJsonTargetFlashMoveBuffCfg(SimpleJSON.JSONNode _json)
    {
        TargetFlashMoveBuffCfg obj = new TargetFlashMoveBuffCfg();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonTargetFlashMoveBuffCfg(TargetFlashMoveBuffCfg _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 目标偏移量
    /// </summary>
    [ShowInInspector, VerticalGroup("特殊")]public float offset { get; set; }

}
}
