//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Datas
{

public sealed partial class ItemCfg :  Bright.Config.BeanBase 
{
    public ItemCfg(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        name = _buf.ReadString();
        imgPath = _buf.ReadString();
        des = _buf.ReadString();
        PostInit();
    }

    public static ItemCfg DeserializeItemCfg(ByteBuf _buf)
    {
        return new Datas.ItemCfg(_buf);
    }

    public int id { get; private set; }
    public string name { get; private set; }
    public string imgPath { get; private set; }
    public string des { get; private set; }

    public const int __ID__ = 1931547948;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "imgPath:" + imgPath + ","
        + "des:" + des + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
